name: Build
on:
  push:
    branches: [main, "release/*", develop]
  pull_request:
    branches: [main, "release/*", develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16.x"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests
          name: codecov-chromiumly
          fail_ci_if_error: true
          verbose: true
